export const SALON_INFO = {
  name: "King and Queen Salon",
  address: "Avenue du Gouverneur Bukavu RDC",
  phones: [
    "+243 976527237",
    "+243 994155412",
    "+243 854123658",
    "+243 890357766",
    "+243 897758610",
    "+243 897986067",
  ],
  hours: {
    open: "07:00",
    close: "21:00",
    days: "Tous les jours",
  },
};

export const SERVICES_DATA = [
  {
    id: "1",
    name: "Soins de visage",
    description: "Traitement complet du visage pour une peau rayonnante",
    priceMin: 10,
    priceMax: null,
    duration: 45,
    category: "Soins",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "2",
    name: "Coiffure homme",
    description: "Coupe et style pour hommes",
    priceMin: 3,
    priceMax: null,
    duration: 30,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "3",
    name: "Draid Locks",
    description: "Tresses et locks de qualité professionnelle",
    priceMin: 20,
    priceMax: 60,
    duration: 120,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "4",
    name: "Coiffure dame cérémonie",
    description: "Coiffure élégante pour occasions spéciales",
    priceMin: 10,
    priceMax: null,
    duration: 90,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "5",
    name: "Manucure",
    description: "Soin des ongles et des mains",
    priceMin: 5,
    priceMax: 10,
    duration: 45,
    category: "Soins",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "6",
    name: "Tresse",
    description: "Tresses variées selon modèle choisi",
    priceMin: 2,
    priceMax: 40,
    duration: 120,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "7",
    name: "Maquillage",
    description: "Maquillage professionnel pour toutes occasions",
    priceMin: 5,
    priceMax: 8,
    duration: 45,
    category: "Maquillage",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "8",
    name: "Pédicure",
    description: "Soin complet des pieds et ongles",
    priceMin: 5,
    priceMax: 10,
    duration: 60,
    category: "Soins",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "9",
    name: "Coiffure dame simple",
    description: "Coiffure quotidienne pour dames",
    priceMin: 5,
    priceMax: null,
    duration: 30,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "10",
    name: "Locks",
    description: "Entretien et création de locks",
    priceMin: 5,
    priceMax: null,
    duration: 60,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "11",
    name: "Lave tête",
    description: "Shampooing et soin des cheveux",
    priceMin: 3,
    priceMax: null,
    duration: 20,
    category: "Soins",
    imageUrl: null,
    isActive: true,
  },
  {
    id: "12",
    name: "Twist",
    description: "Coiffure twist tendance",
    priceMin: 10,
    priceMax: null,
    duration: 60,
    category: "Coiffure",
    imageUrl: null,
    isActive: true,
  },
];

export const TIME_SLOTS = [
  "07:00", "08:00", "09:00", "10:00", "11:00", "12:00",
  "13:00", "14:00", "15:00", "16:00", "17:00", "18:00",
  "19:00", "20:00",
];
